[tool.poetry]
name = "notes"
version = "0"
description = "notes"
authors = ["Artur Shiriev <me@shiriev.ru>"]
maintainers = ["Artur Shiriev <me@shiriev.ru>"]
license = "Proprietary"


[tool.poetry.dependencies]
python = ">=3.8,<4.0"
jupyterlab = "*"
